#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xfce4-dev-tools
Version  : 4.12.0
Release  : 5
URL      : http://archive.xfce.org/src/xfce/xfce4-dev-tools/4.12/xfce4-dev-tools-4.12.0.tar.bz2
Source0  : http://archive.xfce.org/src/xfce/xfce4-dev-tools/4.12/xfce4-dev-tools-4.12.0.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: xfce4-dev-tools-bin = %{version}-%{release}
Requires: xfce4-dev-tools-data = %{version}-%{release}
Requires: xfce4-dev-tools-license = %{version}-%{release}
BuildRequires : pkgconfig(glib-2.0)

%description
What is it?
===========
The Xfce development tools are a collection of tools and macros for
Xfce developers and people that want to build Xfce from Git In addition
it contains the Xfce developer's handbook.

%package bin
Summary: bin components for the xfce4-dev-tools package.
Group: Binaries
Requires: xfce4-dev-tools-data = %{version}-%{release}
Requires: xfce4-dev-tools-license = %{version}-%{release}

%description bin
bin components for the xfce4-dev-tools package.


%package data
Summary: data components for the xfce4-dev-tools package.
Group: Data

%description data
data components for the xfce4-dev-tools package.


%package license
Summary: license components for the xfce4-dev-tools package.
Group: Default

%description license
license components for the xfce4-dev-tools package.


%prep
%setup -q -n xfce4-dev-tools-4.12.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542220210
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1542220210
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xfce4-dev-tools
cp COPYING %{buildroot}/usr/share/package-licenses/xfce4-dev-tools/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xdt-autogen
/usr/bin/xdt-commit
/usr/bin/xdt-csource

%files data
%defattr(-,root,root,-)
/usr/share/xfce4/dev-tools/m4macros/xdt-depends.m4
/usr/share/xfce4/dev-tools/m4macros/xdt-features.m4
/usr/share/xfce4/dev-tools/m4macros/xdt-i18n.m4
/usr/share/xfce4/dev-tools/m4macros/xdt-python.m4
/usr/share/xfce4/dev-tools/m4macros/xdt-xfce.m4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xfce4-dev-tools/COPYING
