#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xfce4-dev-tools
Version  : 4.18.0
Release  : 13
URL      : https://archive.xfce.org/src/xfce/xfce4-dev-tools/4.18/xfce4-dev-tools-4.18.0.tar.bz2
Source0  : https://archive.xfce.org/src/xfce/xfce4-dev-tools/4.18/xfce4-dev-tools-4.18.0.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: xfce4-dev-tools-bin = %{version}-%{release}
Requires: xfce4-dev-tools-license = %{version}-%{release}
Requires: xfce4-dev-tools-man = %{version}-%{release}
BuildRequires : pkgconfig(glib-2.0)

%description
[![License](https://img.shields.io/badge/License-GPL%20v2-blue.svg)](https://gitlab.xfce.org/xfce/xfce4-dev-tools/-/blob/master/COPYING)

%package bin
Summary: bin components for the xfce4-dev-tools package.
Group: Binaries
Requires: xfce4-dev-tools-license = %{version}-%{release}

%description bin
bin components for the xfce4-dev-tools package.


%package dev
Summary: dev components for the xfce4-dev-tools package.
Group: Development
Requires: xfce4-dev-tools-bin = %{version}-%{release}
Provides: xfce4-dev-tools-devel = %{version}-%{release}
Requires: xfce4-dev-tools = %{version}-%{release}

%description dev
dev components for the xfce4-dev-tools package.


%package license
Summary: license components for the xfce4-dev-tools package.
Group: Default

%description license
license components for the xfce4-dev-tools package.


%package man
Summary: man components for the xfce4-dev-tools package.
Group: Default

%description man
man components for the xfce4-dev-tools package.


%prep
%setup -q -n xfce4-dev-tools-4.18.0
cd %{_builddir}/xfce4-dev-tools-4.18.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1671134823
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1671134823
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xfce4-dev-tools
cp %{_builddir}/xfce4-dev-tools-%{version}/COPYING %{buildroot}/usr/share/package-licenses/xfce4-dev-tools/4cc77b90af91e615a64ae04893fdffa7939db84c
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xdt-autogen
/usr/bin/xdt-csource
/usr/bin/xfce-build
/usr/bin/xfce-do-release
/usr/bin/xfce-get-release-notes
/usr/bin/xfce-get-translations
/usr/bin/xfce-update-news

%files dev
%defattr(-,root,root,-)
/usr/share/aclocal/*.m4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xfce4-dev-tools/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xdt-csource.1
