#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xfce4-dev-tools
Version  : 4.4.0
Release  : 1
URL      : http://users.xfce.org/~benny/files/xfce4-dev-tools/4.4/xfce4-dev-tools-4.4.0.tar.gz
Source0  : http://users.xfce.org/~benny/files/xfce4-dev-tools/4.4/xfce4-dev-tools-4.4.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: xfce4-dev-tools-bin
Requires: xfce4-dev-tools-data

%description


%package bin
Summary: bin components for the xfce4-dev-tools package.
Group: Binaries
Requires: xfce4-dev-tools-data

%description bin
bin components for the xfce4-dev-tools package.


%package data
Summary: data components for the xfce4-dev-tools package.
Group: Data

%description data
data components for the xfce4-dev-tools package.


%prep
%setup -q -n xfce4-dev-tools-4.4.0

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xdt-autogen

%files data
%defattr(-,root,root,-)
/usr/share/xfce4/dev-tools/m4macros/xdt-depends.m4
/usr/share/xfce4/dev-tools/m4macros/xdt-features.m4
/usr/share/xfce4/dev-tools/m4macros/xdt-i18n.m4
/usr/share/xfce4/dev-tools/m4macros/xdt-python.m4
/usr/share/xfce4/dev-tools/m4macros/xdt-xfce.m4
